aliases: &stack
  # stacks

  # eighth-x
  stack-eighth-x: 
    value: '{!space-eighth-x}'
  stack-eighth-x-squish: 
    value: '{!space-eighth-x-squish} {!space-eighth-x}'
  stack-eighth-x-stretch: 
    value: '{!space-eighth-x-stretch} {!space-eighth-x}'
  # quarter-x
  stack-quarter-x: 
    value: '{!space-quarter-x}'
  stack-quarter-x-squish: 
    value: '{!space-quarter-x-squish} {!space-quarter-x}'
  stack-quarter-x-stretch: 
    value: '{!space-quarter-x-stretch} {!space-quarter-x}'
  # half-x
  stack-half-x: 
    value: '{!space-half-x}'
  stack-half-x-squish: 
    value: '{!space-half-x-squish} {!space-half-x}'
  stack-half-x-stretch: 
    value: '{!space-half-x-stretch} {!space-half-x}'
  # three-quarter-x
  stack-three-quarter-x: 
    value: '{!space-three-quarter-x}'
  stack-three-quarter-x-squish: 
    value: '{!space-three-quarter-x-squish} {!space-three-quarter-x}'
  stack-three-quarter-x-stretch: 
    value: '{!space-three-quarter-x-stretch} {!space-three-quarter-x}'
  # 1-x
  stack-1-x: 
    value: '{!space-1-x}'
  stack-1-x-squish: 
    value: '{!space-1-x-squish} {!space-1-x}'
  stack-1-x-stretch: 
    value: '{!space-1-x-stretch} {!space-1-x}'
  # 1-and-a-half-x
  stack-1-and-a-half-x: 
    value: '{!space-1-and-a-half-x}'
  stack-1-and-a-half-x-squish: 
    value: '{!space-1-and-a-half-x-squish} {!space-1-and-a-half-x}'
  stack-1-and-a-half-x-stretch: 
    value: '{!space-1-and-a-half-x-stretch} {!space-1-and-a-half-x}'
  # 2-x
  stack-2-x: 
    value: '{!space-2-x}'
  stack-2-x-squish: 
    value: '{!space-2-x-squish} {!space-2-x}'
  stack-2-x-stretch: 
    value: '{!space-2-x-stretch} {!space-2-x}'
  # 4-x
  stack-4-x: 
    value: '{!space-4-x}'
  stack-4-x-squish: 
    value: '{!space-4-x-squish} {!space-4-x}'
  stack-4-x-stretch: 
    value: '{!space-4-x-stretch} {!space-4-x}'

props: *stack
global:
  category: foundations
  type: stack
imports: 
  - ./space.yml